spring:
  datasource:
    account:
      url: jdbc:mysql://localhost:3306/account1
      username: root
      password: 123
      driver-class-name: com.mysql.jdbc.Driver
    order:
      url: jdbc:mysql://localhost:3306/order1
      username: root
      password: 123
      driver-class-name: com.mysql.jdbc.Driver